/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hteng_study_ndk_NDKManager */

#ifndef _Included_com_hteng_study_ndk_NDKManager
#define _Included_com_hteng_study_ndk_NDKManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hteng_study_ndk_NDKManager
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hteng_study_ndk_NDKManager_getString
  (JNIEnv *, jclass);

/*
 * Class:     com_hteng_study_ndk_NDKManager
 * Method:    getStringFomc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hteng_study_ndk_NDKManager_getStringFomc
  (JNIEnv *, jobject);

/*
 * Class:     com_hteng_study_ndk_NDKManager
 * Method:    accessField
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hteng_study_ndk_NDKManager_accessField
  (JNIEnv *, jobject);

/*
 * Class:     com_hteng_study_ndk_NDKManager
 * Method:    accessStaticField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hteng_study_ndk_NDKManager_accessStaticField
  (JNIEnv *, jobject);

/*
 * Class:     com_hteng_study_ndk_NDKManager
 * Method:    accessMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hteng_study_ndk_NDKManager_accessMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_hteng_study_ndk_NDKManager
 * Method:    accessStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hteng_study_ndk_NDKManager_accessStaticMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_hteng_study_ndk_NDKManager
 * Method:    accessConstructor
 * Signature: ()Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_com_hteng_study_ndk_NDKManager_accessConstructor
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
